<a href="https://colab.research.google.com/github/Anthony18xd/EJERCICIOS-PROPUESTOS/blob/main/EJERCICIO_PRACTICO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

asignaturas = np.array(["Matemáticas", "Física", "Química", "Historia", "Lengua"])
print(asignaturas)

['Matemáticas' 'Física' 'Química' 'Historia' 'Lengua']


In [4]:
asignaturas = np.array(["Matemáticas", "Física", "Química", "Historia", "Lengua"])
for asignatura in asignaturas:
    f"Yo estudio {asignatura}"
    print(f"Yo estudio {asignatura}")

Yo estudio Matemáticas
Yo estudio Física
Yo estudio Química
Yo estudio Historia
Yo estudio Lengua


In [5]:
asignaturas = np.array(["Matemáticas", "Física", "Química", "Historia", "Lengua"])
notas = np.zeros(len(asignaturas))

for i, asignatura in enumerate(asignaturas):
    nota = float(input(f"¿Qué nota has sacado en {asignatura}? "))
    notas[i] = nota

resultados = [f"En {asignaturas[i]} has sacado {notas[i]}" for i in range(len(asignaturas))]
nota_media = np.mean(notas)

¿Qué nota has sacado en Matemáticas? 15
¿Qué nota has sacado en Física? 14
¿Qué nota has sacado en Química? 16
¿Qué nota has sacado en Historia? 02
¿Qué nota has sacado en Lengua? 01


In [6]:
numeros_loteria = np.zeros(6, dtype=int)

for i in range(6):
    numero = int(input(f"Introduce el número {i+1} ganador de la lotería primitiva: "))
    numeros_loteria[i] = numero

numeros_ordenados = np.sort(numeros_loteria)

Introduce el número 1 ganador de la lotería primitiva: 25
Introduce el número 2 ganador de la lotería primitiva: 15
Introduce el número 3 ganador de la lotería primitiva: 16
Introduce el número 4 ganador de la lotería primitiva: 1
Introduce el número 5 ganador de la lotería primitiva: 78
Introduce el número 6 ganador de la lotería primitiva: 56


In [7]:
numeros = np.arange(1, 11)
numeros_inverso = np.flip(numeros)
resultado_string = " , ".join(map(str, numeros_inverso))
print(resultado_string)

10 , 9 , 8 , 7 , 6 , 5 , 4 , 3 , 2 , 1


In [8]:
import string
import numpy as np

abecedario = np.array(list(string.ascii_lowercase))
posiciones = np.arange(1, len(abecedario) + 1)
mask = posiciones % 3 != 0
abecedario_filtrado = abecedario[mask]
print(abecedario_filtrado)

['a' 'b' 'd' 'e' 'g' 'h' 'j' 'k' 'm' 'n' 'p' 'q' 's' 't' 'v' 'w' 'y' 'z']


In [9]:
palabra = input("Introduce una palabra: ").lower()
palabra_array = np.array(list(palabra))
palabra_invertida = np.flip(palabra_array)
es_palindromo = np.array_equal(palabra_array, palabra_invertida)

Introduce una palabra: HOLA


In [10]:
import numpy as np

palabra = input("Introduce una palabra: ").lower()
palabra_array = np.array(list(palabra))
vocales = np.array(['a', 'e', 'i', 'o', 'u'])

print(f"La palabra '{palabra}' contiene:")

for vocal in vocales:
    count = np.sum(palabra_array == vocal)
    print(f"- La vocal '{vocal}' aparece {count} veces.")

Introduce una palabra: OLA
La palabra 'ola' contiene:
- La vocal 'a' aparece 1 veces.
- La vocal 'e' aparece 0 veces.
- La vocal 'i' aparece 0 veces.
- La vocal 'o' aparece 1 veces.
- La vocal 'u' aparece 0 veces.


In [11]:
import numpy as np

precios_lista = [50, 75, 46, 22, 80, 65, 8]
precios_array = np.array(precios_lista)

precio_menor = np.min(precios_array)
precio_mayor = np.max(precios_array)

print(f"Los precios son: {precios_lista}")
print(f"El menor precio es: {precio_menor}")
print(f"El mayor precio es: {precio_mayor}")

Los precios son: [50, 75, 46, 22, 80, 65, 8]
El menor precio es: 8
El mayor precio es: 80


In [12]:
import numpy as np

vector1_list = [1, 2, 3]
vector2_list = [-1, 0, 2]

vector1 = np.array(vector1_list)
vector2 = np.array(vector2_list)

producto_escalar = np.dot(vector1, vector2)

print(f"El vector 1 es: {vector1_list}")
print(f"El vector 2 es: {vector2_list}")
print(f"El producto escalar es: {producto_escalar}")

El vector 1 es: [1, 2, 3]
El vector 2 es: [-1, 0, 2]
El producto escalar es: 5


In [17]:
import numpy as np

matriz1_list = [[1, 2], [3, 4]]
matriz2_list = [[5, 6], [7, 8]]

matriz1 = np.array(matriz1_list)
matriz2 = np.array(matriz2_list)

if matriz1.shape[1] == matriz2.shape[0]:
    producto_matrices = np.dot(matriz1, matriz2)

    print("Matriz 1:")
    display(matriz1)

    print("\nMatriz 2:")
    display(matriz2)

    print("\nProducto de las matrices:")
    display(producto_matrices)
else:
    print("Las matrices no se pueden multiplicar. El número de columnas de la primera matriz debe ser igual al número de filas de la segunda.")

Matriz 1:


array([[1, 2],
       [3, 4]])


Matriz 2:


array([[5, 6],
       [7, 8]])


Producto de las matrices:


array([[19, 22],
       [43, 50]])

In [16]:
import numpy as np

numeros_str = input("Introduce una muestra de números separados por comas: ")

numeros_lista = [float(num.strip()) for num in numeros_str.split(',')]

numeros_array = np.array(numeros_lista)

media = np.mean(numeros_array)
desviacion_tipica = np.std(numeros_array)

print(f"La muestra de números es: {numeros_lista}")
print(f"La media es: {media}")
print(f"La desviación típica es: {desviacion_tipica}")

Introduce una muestra de números separados por comas: 14,2,5,8,7,1,4,7,6,565,4,7,4,8
La muestra de números es: [14.0, 2.0, 5.0, 8.0, 7.0, 1.0, 4.0, 7.0, 6.0, 565.0, 4.0, 7.0, 4.0, 8.0]
La media es: 45.857142857142854
La desviación típica es: 144.016297263716
